openapi: 3.0.1
info:
  title: API per gestione dei libri di libreria
  description: |-
    Questa API consente la gestione dei libri all'interno di una libreria. 
    Include operazioni CRUD principali per la gestione dei libri.
  version: 1.0.0
paths:
  /library-rs-book:
    get:
      operationId: getBooks
      responses:
        default:
          description: default response
          content:
            application/json: {}
    post:
      operationId: addBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /library-rs-book/{id}:
    get:
      operationId: getBookById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: default response
          content:
            application/json: {}
    put:
      operationId: updateBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        default:
          description: default response
          content:
            application/json: {}
    delete:
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /library-rs-book/findByBook:
    post:
      operationId: findBooksByBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /library-rs-book/findByString:
    get:
      operationId: findBooksByString
      parameters:
        - name: param
          in: query
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
components:
  schemas:
    Author:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        id:
          type: integer
          format: int64
    Book:
      type: object
      properties:
        bookId:
          type: integer
          format: int64
        editor:
          $ref: '#/components/schemas/Editor'
        authors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Author'
        title:
          type: string
        isbn:
          type: string
        authorsSet:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Author'
        authorsArray:
          type: array
          items:
            $ref: '#/components/schemas/Author'
    Editor:
      type: object
      properties:
        name:
          type: string
        id:
          type: integer
          format: int64